spring:
  application:
    name: LedgerFxApp
  jmx:
    # 禁用JMX监控功能，减少资源占用，提高启动速度
    enabled: false
  main:
    # 指定应用为非Web应用（控制台/桌面应用），不启动内嵌Web服务器
    web-application-type: none
    # 关闭 Spring Boot 启动时的 ASCII 艺术横幅显示，保持控制台输出简洁
    banner-mode: off

  datasource:
    url: jdbc:h2:file:./data/ledgerfx
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always        # always 每次应用启动时都执行初始化 SQL, 脚本 never 从不执行初始化 SQL 脚本
      platform: h2
      schema-locations: classpath:db/schema.sql
      #data-locations: classpath:db/data.sql

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml  # Mapper XML
  type-aliases-package: com.ledgerfx.domain  # 实体类

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework: INFO
    com.javafx.boot.demo: DEBUG